# app/services/network_builder.py
"""
Reads a .gpkg file from the shared volume, converts it to an EPANET .inp
file, and returns a path to that .inp — ready for EPyT-Flow's ScenarioSimulator.

Pipeline
--------
1. Open the .gpkg with sqlite3.
2. Parse MULTILINESTRING / LINESTRING geometries (custom WKB parser — no
   geopandas or PostGIS needed).
3. Extract unique junction nodes from pipe start/end points.
4. Write a valid EPANET .inp file (INP format sections:
   [JUNCTIONS], [RESERVOIRS], [PIPES], [DEMANDS], [COORDINATES],
   [TIMES], [OPTIONS], [END]).
5. Return the .inp path so the caller can hand it to ScenarioSimulator.

EPyT-Flow then loads the .inp via its own EPANET C-library bindings —
giving access to AbruptLeakage, sensor placement, SCADA data, and all
other EPyT-Flow features.
"""

import logging
import math
import os
import sqlite3
import struct
import tempfile
from typing import Dict, List, Optional, Tuple

from app.core.config import get_settings
from app.core.exceptions import GpkgNotFoundError, InvalidGpkgError

logger = logging.getLogger(__name__)

COORD_PRECISION = 6   # decimal places for node-key rounding


# ── WKB geometry parser ────────────────────────────────────────────────────────

def _parse_gpkg_geometry(blob: bytes) -> List[List[Tuple[float, float]]]:
    """
    Parse a GeoPackage WKB blob → list of coordinate rings [(lon, lat), …].
    Supports LINESTRING (type 2) and MULTILINESTRING (type 5).
    Returns [] for empty/unsupported geometries.
    """
    if blob is None or len(blob) < 9:
        return []

    flags = blob[3]
    if (flags >> 4) & 0x01:          # empty-geometry flag
        return []

    envelope_bytes = {0: 0, 1: 32, 2: 48, 3: 48, 4: 64}
    wkb_offset = 8 + envelope_bytes.get((flags >> 1) & 0x07, 0)
    wkb = blob[wkb_offset:]
    if len(wkb) < 5:
        return []

    endian    = "<" if wkb[0] == 1 else ">"
    geom_type = struct.unpack_from(endian + "I", wkb, 1)[0]

    def read_ring(data: bytes, offset: int):
        n = struct.unpack_from(endian + "I", data, offset)[0]
        offset += 4
        pts = []
        for _ in range(n):
            x, y = struct.unpack_from(endian + "dd", data, offset)
            pts.append((x, y))
            offset += 16
        return pts, offset

    rings: List[List[Tuple[float, float]]] = []
    offset = 5

    if geom_type == 2:
        ring, _ = read_ring(wkb, offset)
        if ring:
            rings.append(ring)
    elif geom_type == 5:
        n_geoms = struct.unpack_from(endian + "I", wkb, offset)[0]
        offset += 4
        for _ in range(n_geoms):
            offset += 5              # byte-order + type
            ring, offset = read_ring(wkb, offset)
            if ring:
                rings.append(ring)

    return rings


def _node_key(lon: float, lat: float) -> str:
    return f"{round(lon, COORD_PRECISION)},{round(lat, COORD_PRECISION)}"


def _haversine_m(lon1, lat1, lon2, lat2) -> float:
    R = 6_371_000.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dl = math.radians(lon2 - lon1)
    dp = math.radians(lat2 - lat1)
    a  = math.sin(dp / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dl / 2) ** 2
    return 2 * R * math.asin(math.sqrt(max(0.0, a)))


def _nearest_node_key(
    lat: float, lon: float,
    node_coords: Dict[str, Tuple[float, float]]
) -> Optional[str]:
    best_key, best_d = None, float("inf")
    for key, (nlon, nlat) in node_coords.items():
        d = _haversine_m(lon, lat, nlon, nlat)
        if d < best_d:
            best_d, best_key = d, key
    return best_key


# ── EPANET .inp writer ─────────────────────────────────────────────────────────

def _sanitise_id(raw: str) -> str:
    """
    EPANET node/link IDs must not contain spaces or semicolons.
    Replace problematic characters with underscores.
    """
    return raw.replace(" ", "_").replace(";", "_").replace(",", "_")


def _write_inp(
    node_coords:      Dict[str, Tuple[float, float]],
    node_demands:     Dict[str, float],
    reservoir_key:    str,
    reservoir_head:   float,
    pipe_defs:        List[dict],
    duration_hrs:     int,
    time_step_min:    int,
    out_path:         str,
) -> None:
    """Write a minimal but valid EPANET .inp file."""

    # build safe ID maps  (raw key → EPANET-safe ID)
    node_id: Dict[str, str] = {k: _sanitise_id(f"N_{i}") for i, k in enumerate(node_coords)}
    res_id  = "RESERVOIR_0"

    lines = []

    # ── [TITLE] ────────────────────────────────────────────────────────────────
    lines += ["[TITLE]", "DUWAS Water Network — generated by EPANET Hydraulic Service", ""]

    # ── [JUNCTIONS] ───────────────────────────────────────────────────────────
    lines += ["[JUNCTIONS]", ";ID              Elev    Demand   Pattern"]
    for key, nid in node_id.items():
        if key == reservoir_key:
            continue
        elev   = 0.0
        demand = node_demands.get(key, 0.0)
        lines.append(f" {nid:<16} {elev:<8.2f} {demand:<8.6f}")
    lines.append("")

    # ── [RESERVOIRS] ──────────────────────────────────────────────────────────
    lines += ["[RESERVOIRS]", ";ID              Head     Pattern"]
    lines.append(f" {res_id:<16} {reservoir_head:<8.2f}")
    lines.append("")

    # ── [TANKS] ───────────────────────────────────────────────────────────────
    lines += ["[TANKS]", ""]

    # ── [PIPES] ───────────────────────────────────────────────────────────────
    lines += ["[PIPES]", ";ID              Node1           Node2           Length  Diameter  Roughness  MinorLoss  Status"]
    for i, p in enumerate(pipe_defs):
        pid   = f"P_{i}"
        n1    = node_id.get(p["start_key"])
        n2    = node_id.get(p["end_key"])
        if not n1 or not n2:
            continue
        # start node may be the reservoir
        if p["start_key"] == reservoir_key:
            n1 = res_id
        if p["end_key"] == reservoir_key:
            n2 = res_id
        lines.append(
            f" {pid:<16} {n1:<16} {n2:<16} "
            f"{p['length_m']:<8.2f} {p['diam_mm']:<10.2f} "
            f"{p['roughness']:<11.2f} 0          Open"
        )
    lines.append("")

    # ── [PUMPS] / [VALVES] ────────────────────────────────────────────────────
    lines += ["[PUMPS]", "", "[VALVES]", ""]

    # ── [DEMANDS] ─────────────────────────────────────────────────────────────
    lines += ["[DEMANDS]", ";Junction        Demand   Pattern   Category"]
    lines.append("")

    # ── [STATUS] ──────────────────────────────────────────────────────────────
    lines += ["[STATUS]", ""]

    # ── [PATTERNS] / [CURVES] ─────────────────────────────────────────────────
    lines += ["[PATTERNS]", "", "[CURVES]", ""]

    # ── [CONTROLS] ────────────────────────────────────────────────────────────
    lines += ["[CONTROLS]", ""]

    # ── [RULES] ───────────────────────────────────────────────────────────────
    lines += ["[RULES]", ""]

    # ── [ENERGY] ──────────────────────────────────────────────────────────────
    lines += ["[ENERGY]", " Global Efficiency  75", " Global Price      0", " Demand Charge     0", ""]

    # ── [EMITTERS] ────────────────────────────────────────────────────────────
    lines += ["[EMITTERS]", ""]

    # ── [QUALITY] ─────────────────────────────────────────────────────────────
    lines += ["[QUALITY]", ""]

    # ── [SOURCES] ─────────────────────────────────────────────────────────────
    lines += ["[SOURCES]", ""]

    # ── [REACTIONS] ───────────────────────────────────────────────────────────
    lines += ["[REACTIONS]", " Order Bulk            1", " Order Tank            1", " Order Wall            1",
              " Global Bulk           0", " Global Wall           0", " Limiting Potential    0",
              " Roughness Correlation 0", ""]

    # ── [MIXING] ──────────────────────────────────────────────────────────────
    lines += ["[MIXING]", ""]

    # ── [TIMES] ───────────────────────────────────────────────────────────────
    h, m = divmod(duration_hrs * 60, 60)
    ts_h, ts_m = divmod(time_step_min, 60)
    lines += [
        "[TIMES]",
        f" Duration            {h}:{m:02d}",
        f" Hydraulic Timestep  {ts_h}:{ts_m:02d}",
        f" Quality Timestep    {ts_h}:{ts_m:02d}",
        f" Pattern Timestep    {ts_h}:{ts_m:02d}",
        f" Pattern Start       0:00",
        f" Report Timestep     {ts_h}:{ts_m:02d}",
        f" Report Start        0:00",
        " Start ClockTime     12 am",
        " Statistic           NONE",
        "",
    ]

    # ── [REPORT] ──────────────────────────────────────────────────────────────
    lines += ["[REPORT]", " Status    Yes", " Summary   No", " Page      0", ""]

    # ── [OPTIONS] ─────────────────────────────────────────────────────────────
    lines += [
        "[OPTIONS]",
        " Units               CMH",       # cubic metres per hour
        " Headloss            H-W",       # Hazen-Williams
        " Specific Gravity    1",
        " Viscosity           1",
        " Trials              40",
        " Accuracy            0.001",
        " CHECKFREQ           2",
        " MAXCHECK            10",
        " DAMPLIMIT           0",
        " Unbalanced          Continue   10",
        " Pattern             1",
        " Demand Multiplier   1.0",
        " Emitter Exponent    0.5",
        " Quality             Age   hours",
        " Diffusivity         1",
        " Tolerance           0.01",
        "",
    ]

    # ── [COORDINATES] ─────────────────────────────────────────────────────────
    lines += ["[COORDINATES]", ";Node            X-Coord         Y-Coord"]
    for key, nid in node_id.items():
        if key == reservoir_key:
            continue
        lon, lat = node_coords[key]
        lines.append(f" {nid:<16} {lon:<16.8f} {lat:<16.8f}")
    # reservoir coordinate
    res_lon, res_lat = node_coords[reservoir_key]
    lines.append(f" {res_id:<16} {res_lon:<16.8f} {res_lat:<16.8f}")
    lines.append("")

    # ── [VERTICES] ────────────────────────────────────────────────────────────
    lines += ["[VERTICES]", ""]

    # ── [LABELS] / [BACKDROP] / [TAGS] ────────────────────────────────────────
    lines += ["[LABELS]", "", "[BACKDROP]", "", "[TAGS]", ""]

    # ── [END] ─────────────────────────────────────────────────────────────────
    lines.append("[END]")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    logger.info("Wrote EPANET .inp to %s  (%d lines)", out_path, len(lines))


# ── public API ─────────────────────────────────────────────────────────────────

def list_gpkg_files() -> List[str]:
    settings = get_settings()
    gpkg_dir = settings.gpkg_dir
    if not os.path.isdir(gpkg_dir):
        return []
    return sorted(f for f in os.listdir(gpkg_dir) if f.lower().endswith(".gpkg"))


def gpkg_full_path(filename: str) -> str:
    settings = get_settings()
    safe     = os.path.basename(filename)
    path     = os.path.join(settings.gpkg_dir, safe)
    if not os.path.isfile(path):
        raise GpkgNotFoundError(filename)
    return path


def build_inp_from_gpkg(
    filename:       str,
    pipe_status:    str   = "OPERATIONAL",
    base_demand:    float = 0.001,        # m³/s  (converted to CMH for EPANET)
    reservoir_head: float = 50.0,         # metres
    duration_hrs:   int   = 24,
    time_step_min:  int   = 60,
    extra_demands:  Optional[List[dict]] = None,
    inp_dir:        Optional[str]        = None,
) -> str:
    """
    Convert a .gpkg file to an EPANET .inp file and return its path.

    Parameters
    ----------
    filename       : basename of the .gpkg file (e.g. "duwas_network_clean.gpkg")
    pipe_status    : SQL filter for the STATUS field
    base_demand    : base demand per junction in m³/s
                     (written as CMH = m³/h to the .inp)
    reservoir_head : head at the reservoir node (metres)
    duration_hrs   : simulation duration for [TIMES] section
    time_step_min  : hydraulic time step in minutes
    extra_demands  : [{"lat": float, "lon": float, "demand_m3s": float}, …]
    inp_dir        : directory to write the .inp file;
                     defaults to a system temp directory

    Returns
    -------
    Absolute path to the generated .inp file.
    """
    path = gpkg_full_path(filename)
    logger.info("Loading .gpkg: %s  (status=%s)", filename, pipe_status)

    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row

    # detect layer name
    cur   = conn.cursor()
    layer_row = cur.execute("SELECT table_name FROM gpkg_contents LIMIT 1").fetchone()
    if not layer_row:
        conn.close()
        raise InvalidGpkgError("No layers found in the GeoPackage.")
    layer = layer_row[0]

    cur.execute(f"""
        SELECT fid, geom, intdiammm, roughness, length3dig, pipelength
        FROM   {layer}
        WHERE  status = ?
          AND  geom IS NOT NULL
    """, (pipe_status,))
    rows = cur.fetchall()
    conn.close()
    logger.info("Fetched %d pipe rows", len(rows))

    if not rows:
        raise InvalidGpkgError(
            f"No pipes with status='{pipe_status}' found. "
            "Check status values in the GeoPackage."
        )

    # ── collect nodes & pipe definitions ──────────────────────────────────────
    node_coords:   Dict[str, Tuple[float, float]] = {}
    pipe_defs:     List[dict]                     = []

    for row in rows:
        rings = _parse_gpkg_geometry(bytes(row["geom"]))
        if not rings:
            continue

        l3d = row["length3dig"]
        eff_len = float(l3d) if l3d and float(l3d) > 0 else None

        for ring in rings:
            if len(ring) < 2:
                continue

            start_lon, start_lat = ring[0]
            end_lon,   end_lat   = ring[-1]

            if eff_len is None:
                eff_len = _haversine_m(start_lon, start_lat, end_lon, end_lat)

            for lon, lat in [(start_lon, start_lat), (end_lon, end_lat)]:
                key = _node_key(lon, lat)
                if key not in node_coords:
                    node_coords[key] = (lon, lat)

            diam_mm   = float(row["intdiammm"]) if row["intdiammm"] else 100.0
            roughness = float(row["roughness"])  if row["roughness"] and float(row["roughness"]) > 0 else 130.0

            pipe_defs.append({
                "fid":       row["fid"],
                "start_key": _node_key(start_lon, start_lat),
                "end_key":   _node_key(end_lon,   end_lat),
                "length_m":  max(eff_len, 0.1),
                "diam_mm":   diam_mm,
                "roughness": roughness,
            })

    logger.info("Unique nodes: %d  |  pipe segments: %d", len(node_coords), len(pipe_defs))

    # ── choose reservoir: node closest to centroid ─────────────────────────────
    all_lons = [c[0] for c in node_coords.values()]
    all_lats = [c[1] for c in node_coords.values()]
    cx, cy   = sum(all_lons) / len(all_lons), sum(all_lats) / len(all_lats)
    reservoir_key = _nearest_node_key(cy, cx, node_coords)
    logger.info("Reservoir at node key: %s", reservoir_key)

    # ── diagnostics: node degree & connectivity ───────────────────────────────
    from collections import Counter, defaultdict, deque

    degree = Counter()
    graph = defaultdict(set)
    for p in pipe_defs:
        s, e = p["start_key"], p["end_key"]
        degree[s] += 1
        degree[e] += 1
        graph[s].add(e)
        graph[e].add(s)

    total_nodes = len(node_coords)
    deg1 = sum(1 for d in degree.values() if d == 1)
    isolated = sum(1 for d in degree.values() if d == 0)
    logger.info("Degree stats: total=%d  isolated=%d  degree1=%d", total_nodes, isolated, deg1)

    # connected components
    visited = set()
    components = []
    for node in graph:
        if node in visited:
            continue
        size = 0
        q = deque([node])
        while q:
            n = q.popleft()
            if n in visited:
                continue
            visited.add(n)
            size += 1
            for nb in graph[n]:
                if nb not in visited:
                    q.append(nb)
        components.append(size)
    components.sort(reverse=True)
    logger.info("Connected components: %d  (largest: %d nodes)", len(components), components[0] if components else 0)

    # ── Choose reservoir: prefer the most-connected node (highest degree)
    if degree:
        reservoir_key = max(degree, key=degree.get)
        logger.info("Reservoir chosen at node key: %s  (degree=%d)", reservoir_key, degree[reservoir_key])
    else:
        # fallback to centroid-based reservoir if degree info is unavailable
        all_lons = [c[0] for c in node_coords.values()]
        all_lats = [c[1] for c in node_coords.values()]
        cx, cy   = sum(all_lons) / len(all_lons), sum(all_lats) / len(all_lats)
        reservoir_key = _nearest_node_key(cy, cx, node_coords)
        logger.info("Fallback reservoir at node key: %s", reservoir_key)

    # ── build demand map (m³/s → CMH for EPANET) ─────────────────────────────
    # EPANET with Units=CMH expects demands in m³/h
    base_cmh = base_demand * 3600.0

    node_demands: Dict[str, float] = {
        k: 0.0 if k == reservoir_key else base_cmh
        for k in node_coords
    }

    if extra_demands:
        for ed in extra_demands:
            key = _nearest_node_key(ed["lat"], ed["lon"], node_coords)
            if key and key != reservoir_key:
                node_demands[key] = node_demands.get(key, 0.0) + ed["demand_m3s"] * 3600.0
        logger.info("Applied %d extra demand entries", len(extra_demands))

    # ── deduplicate pipes ──────────────────────────────────────────────────────
    seen: set = set()
    unique_pipes = []
    for p in pipe_defs:
        key = (p["start_key"], p["end_key"])
        if key not in seen and p["start_key"] != p["end_key"]:
            seen.add(key)
            unique_pipes.append(p)

    logger.info("Unique pipe segments after deduplication: %d", len(unique_pipes))

    # ── write .inp file ────────────────────────────────────────────────────────
    if inp_dir is None:
        inp_dir = tempfile.gettempdir()
    os.makedirs(inp_dir, exist_ok=True)

    base_name = os.path.splitext(os.path.basename(filename))[0]
    inp_path  = os.path.join(inp_dir, f"{base_name}.inp")

    _write_inp(
        node_coords    = node_coords,
        node_demands   = node_demands,
        reservoir_key  = reservoir_key,
        reservoir_head = reservoir_head,
        pipe_defs      = unique_pipes,
        duration_hrs   = duration_hrs,
        time_step_min  = time_step_min,
        out_path       = inp_path,
    )

    return inp_path
